name: woolies
version: 0.1.0
author: Peter Siroki <psiroki@skawa.hu>
description: A simple countdown overlay generator
homepage: https://github.com/gothamgasworks/woolies

dependencies:
  crc32:
  dart_to_js_script_rewriter:
transformers:
- $dart2js:
    minify: true
    csp: true
- dart_to_js_script_rewriter
